{
 "title": "Linkerd / Namespace",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(process_start_time_seconds{deployment!=\"\"}, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployments",
    "query": "label_values(process_start_time_seconds{namespace=\"$namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "GLOBAL SUCCESS RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=~\"$namespace\", deployment=~\"$deployment\"}[30s])) / sum(irate(response_total{namespace=~\"$namespace\", deployment=~\"$deployment\"}[30s]))"
    }
   ]
  },
  {
   "title": "GLOBAL REQUEST VOLUME",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=~\"$namespace\", deployment=~\"$deployment\"}[30s]))"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS MONITORED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(request_total{namespace=~\"$namespace\", deployment=~\"$deployment\"}) by (namespace, deployment))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>TOP LINE</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=~\"$namespace\", deployment=~\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=~\"$namespace\", deployment=~\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=~\"$namespace\", deployment=~\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=~\"$namespace\", deployment=~\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=~\"$namespace\", deployment=~\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>DEPLOYMENTS</span>\n</div>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "deployment" },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 71 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 101 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 101 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 111 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 111 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 121 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 121 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  }
 ]
}